=== uncefact/tests-untp/packages/untp-utils/artefacts/schema/untp/0.6.1/dia.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": true,
  "properties": {
    "type": {
      "type": "array",
      "readOnly": true,
      "default": ["DigitalIdentityAnchor", "VerifiableCredential"],
      "items": {
        "type": "string"
      },
      "allOf": [
        {
          "contains": {
            "const": "DigitalIdentityAnchor",
            "minContains": 1
          }
        },
        {
          "contains": {
            "const": "VerifiableCredential",
            "minContains": 1
          }
        }
      ]
    },
    "@context": {
      "example": ["https://www.w3.org/ns/credentials/v2", "https://test.uncefact.org/vocabulary/untp/dia/0.6.1/"],
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "A list of JSON-LD context URIs that define the semantic meaning of properties within the credential. ",
      "readOnly": true,
      "prefixItems": [
        {
          "const": "https://www.w3.org/ns/credentials/v2",
          "type": "string"
        },
        {
          "const": "https://test.uncefact.org/vocabulary/untp/dia/0.6.1/",
          "type": "string"
        }
      ],
      "default": ["https://www.w3.org/ns/credentials/v2", "https://test.uncefact.org/vocabulary/untp/dia/0.6.1/"],
      "minItems": 2,
      "uniqueItems": true
    },
    "id": {
      "example": "https://example-company.com/credentials/2a423366-a0d6-4855-ba65-2e0c926d09b0",
      "type": "string",
      "format": "uri",
      "description": "A unique identifier (URI) assigned to the product passport. May be a UUID"
    },
    "issuer": {
      "$ref": "#/$defs/CredentialIssuer",
      "description": "The organisation that is the issuer of this VC. Note that the \"id\" property MUST be a W3C DID.  Other identifiers such as tax registration numbers can be listed in the \"otherIdentifiers\" property."
    },
    "validFrom": {
      "pattern": "^-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))$",
      "example": "2024-03-15T12:00:00Z",
      "type": "string",
      "format": "date-time",
      "description": "The date and time from which the credential is valid."
    },
    "validUntil": {
      "pattern": "^-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))$",
      "example": "2034-03-15T12:00:00Z",
      "type": "string",
      "format": "date-time",
      "description": "The expiry date (if applicable) of this verifiable credential."
    },
    "credentialSubject": {
      "$ref": "#/$defs/RegisteredIdentity",
      "description": "The registered identity from the authoritative register that is the subject of this credential"
    }
  },
  "description": "The Digital Identity Anchor (DIA) is a very simple credential that is issued by a trusted authority and asserts an equivalence between a member identity as known to the authority (eg a VAT number) and one or more decentralised identifiers (DIDs) held by the member.  ",
  "required": ["@context", "id", "issuer"],
  "$defs": {
    "CredentialIssuer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "array",
          "readOnly": true,
          "default": ["CredentialIssuer"],
          "items": {
            "type": "string"
          },
          "allOf": [
            {
              "contains": {
                "const": "CredentialIssuer",
                "minContains": 1
              }
            }
          ]
        },
        "id": {
          "example": "did:web:identifiers.example-company.com:12345",
          "type": "string",
          "format": "uri",
          "description": "The W3C DID of the issuer - should be a did:web or did:webvh"
        },
        "name": {
          "example": "Example Company Pty Ltd",
          "type": "string",
          "description": "The name of the issuer person or organisation"
        },
        "issuerAlsoKnownAs": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "example": "https://abr.business.gov.au/ABN/View?abn=90664869327",
                "type": "string",
                "format": "uri",
                "description": "The globally unique ID of the party as a URI, ideally as a resolvable ID. "
              },
              "name": {
                "example": "Sample Company Pty Ltd.",
                "type": "string",
                "description": "The registered name of the party within the identifier scheme."
              },
              "registeredId": {
                "example": 90664869327,
                "type": "string",
                "description": "The registration number (alphanumeric) of the Party within the register. Unique within the register."
              }
            },
            "required": ["id", "name"]
          },
          "description": "An optional list of other registered identifiers for this credential issuer "
        }
      },
      "description": "The issuer party (person or organisation) of a verifiable credential.",
      "required": ["id", "name"]
    },
    "RegisteredIdentity": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "type": {
          "type": "array",
          "readOnly": true,
          "default": ["RegisteredIdentity"],
          "items": {
            "type": "string"
          },
          "allOf": [
            {
              "contains": {
                "const": "RegisteredIdentity",
                "minContains": 1
              }
            }
          ]
        },
        "id": {
          "example": "did:web:samplecompany.com/123456789",
          "type": "string",
          "format": "uri",
          "description": "The DID that is controlled by the registered member and is linked to the registeredID through this Identity Anchor credential"
        },
        "name": {
          "example": "Sample business Ltd",
          "type": "string",
          "description": "The registered name of the entity within the identifier scheme.  Examples: product - EV battery 300Ah, Party - Sample Company Pty Ltd,  Facility - Green Acres battery factory"
        },
        "registeredId": {
          "example": 123456789,
          "type": "string",
          "description": "The registration number (alphanumeric) of the entity within the register. Unique within the register."
        },
        "idScheme": {
          "$ref": "#/$defs/IdentifierScheme",
          "description": "An identifier registration scheme for products, facilities, or organisations. Typically operated by a state, national or global authority."
        },
        "registerType": {
          "type": "string",
          "enum": ["Product", "Facility", "Business", "Trademark", "Land", "Accreditation"],
          "example": "Product",
          "description": "The thematic purpose of the register - organisations, facilities, products, trademarks, etc"
        },
        "registrationScopeList": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uri"
          },
          "description": "List of URIs the represent the role/scopes of membership for the register. For example [\"https://abr.business.gov.au/Help/EntityTypeDescription?Id=19\"]"
        }
      },
      "description": "The identity anchor is a mapping between a registery member identity and one or more decentralised identifiers owned by the member. It may also list a set of membership scopes.",
      "required": ["id", "name"]
    },
    "IdentifierScheme": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "array",
          "readOnly": true,
          "default": ["IdentifierScheme"],
          "items": {
            "type": "string"
          },
          "allOf": [
            {
              "contains": {
                "const": "IdentifierScheme",
                "minContains": 1
              }
            }
          ]
        },
        "id": {
          "example": "https://id.gs1.org/01/",
          "type": "string",
          "format": "uri",
          "description": "The globally unique identifier of the registration scheme. The scheme should be registered and discoverable from vocabulary.uncefact.org/identifierSchemes"
        },
        "name": {
          "example": "Global Trade Identification Number (GTIN)",
          "type": "string",
          "description": "The name of the identifier scheme. "
        }
      },
      "description": "An identifier registration scheme for products, facilities, or organisations. Typically operated by a state, national or global authority."
    }
  }
}

=== uncefact/tests-untp/packages/reference-implementation/src/templates/v0.6.1/digital_identity_anchor/example-data.json
{
  "type": ["DigitalIdentityAnchor", "VerifiableCredential"],
  "@context": ["https://www.w3.org/ns/credentials/v2", "https://test.uncefact.org/vocabulary/untp/dia/0.6.1/"],
  "id": "https://example-company.com/credentials/2a423366-a0d6-4855-ba65-2e0c926d09b0",
  "issuer": {
    "type": ["CredentialIssuer"],
    "id": "did:web:identifiers.example-company.com:12345",
    "name": "Example Company Pty Ltd",
    "issuerAlsoKnownAs": [
      {
        "id": "https://abr.business.gov.au/ABN/View?abn=90664869327",
        "name": "Sample Company Pty Ltd.",
        "registeredId": "90664869327",
        "idScheme": {
          "type": ["IdentifierScheme"],
          "id": "https://id.gs1.org/01/",
          "name": "Global Trade Identification Number (GTIN)"
        }
      }
    ]
  },
  "validFrom": "2024-03-15T12:00:00Z",
  "validUntil": "2034-03-15T12:00:00Z",
  "credentialSubject": {
    "type": ["RegisteredIdentity"],
    "id": "did:web:samplecompany.com/123456789",
    "name": "Sample business Ltd",
    "registeredId": "123456789",
    "idScheme": {
      "type": ["IdentifierScheme"],
      "id": "https://id.gs1.org/01/",
      "name": "Global Trade Identification Number (GTIN)"
    },
    "registerType": "Business",
    "registrationScopeList": ["https://jargon.sh"]
  }
}

=== uncefact/tests-untp/packages/untp-test-suite/credentials/digitalFacilityRecord/DigitalFacilityRecord_instance-0.3.10.json
{
  "type": ["DigitalFacilityRecord", "VerifiableCredential"],
  "@context": ["https://www.w3.org/ns/credentials/v2", "https://vocabulary.uncefact.org/untp/dfr/0.3.10"],
  "id": "https://example-company.com/credentials/2a423366-a0d6-4855-ba65-2e0c926d09b0",
  "issuer": {
    "type": ["CredentialIssuer"],
    "id": "did:web:identifiers.example-company.com:12345",
    "name": "Example Company Pty Ltd"
  },
  "validFrom": "2024-03-15T12:00:00Z",
  "validUntil": "2034-03-15T12:00:00Z",
  "credentialSubject": {
    "type": ["Facility", "Entity"],
    "id": "https://id.gs1.org/gln/0614141123452",
    "name": "Example facility 7",
    "locationInformation": {
      "type": ["Location"],
      "geoLocation": {
        "type": "Point",
        "coordinates": [149.1283, -35.283]
      },
      "geoBoundary": {
        "type": "Polygon",
        "coordinates": [
          [
            [149.1283, -35.283],
            [149.1293, -35.284],
            [149.1288, -35.282],
            [149.1283, -35.283]
          ]
        ]
      }
    }
  }
}

=== uncefact/tests-untp/packages/untp-test-suite-mocha/example-credentials/conformity-credential-simple.json
{
  "type": [
    "DigitalConformityCredential",
    "VerifiableCredential"
  ],
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    "https://test.uncefact.org/vocabulary/untp/dcc/0.6.0-beta12/"
  ],
  "id": "http://localhost/credentials/untp-dcc-simple.json",
  "issuer": {
    "type": [
      "CredentialIssuer"
    ],
    "id": "did:web:identifiers.electronic-certifier.com",
    "name": "Electronic Certifier Pty Ltd"
  },
  "validFrom": "2024-03-15T12:00:00Z",
  "validUntil": "2034-03-15T12:00:00Z",
  "credentialSubject": {
    "type": [
      "ConformityAttestation",
      "Attestation"
    ],
    "id": "https://sample-certifiers.com/attestations/12345",
    "name": "Carbon Lifecycle assessment 12345567",
    "assessorLevel": "3rdParty",
    "assessmentLevel": "Accredited",
    "attestationType": "certification",
    "description": "A life-cycle assessment of the battery  emissions intensity according to the Global Battery Alliance rule-book.",
    "issuedToParty": {
      "id": "https://abr.business.gov.au/ABN/View?abn=90664869327",
      "name": "Battery Company Pty Ltd.",
      "registeredId": "90664869327",
      "idScheme": {
        "type": [
          "IdentifierScheme"
        ],
        "id": "https://id.gs1.org/01/",
        "name": "Global Trade Identification Number (GTIN)"
      }
    },
    "assessment": [
      {
        "type": [
          "ConformityAssessment",
          "Declaration"
        ],
        "assessmentDate": "2024-03-15",
        "id": "https://exampleCAB.com/38f73303-a39e-45a7-b8b7-e73517548f27/01",
        "assessedProduct": [
          {
            "product": {
              "id": "https://id.gs1.org/01/09520123456788/21/12345",
              "name": "EV battery 300Ah",
              "registeredId": "09520123456788.21.12345",
              "idScheme": {
                "type": [
                  "IdentifierScheme"
                ],
                "id": "https://id.gs1.org/01/",
                "name": "Global Trade Identification Number (GTIN)"
              }
            },
            "IDverifiedByCAB": true
          }
        ],
        "assessmentCriteria": [
          {
            "id": "https://www.globalbattery.org/media/publications/gba-rulebook-v2.0-master.pdf#BatteryAssembly",
            "name": "GBA Battery rule book v2.0 battery assembly guidelines",
            "description": "The battery assembly guidelines from the Global Battery Alliance rule book v2.0."
          }
        ],
        "declaredValue": [
          {
            "metricName": "GHG emissions intensity",
            "metricValue": {
              "value": 10,
              "unit": "KGM"
            },
            "score": "BB",
            "accuracy": 0.05
          }
        ],
        "conformance": true,
        "conformityTopic": "environment.emissions"
      },
      {
        "type": [
          "ConformityAssessment",
          "Declaration"
        ],
        "assessmentDate": "2024-03-15",
        "id": "https://exampleCAB.com/38f73303-a39e-45a7-b8b7-e73517548f27/01",
        "assessedProduct": [
          {
            "product": {
              "id": "https://id.gs1.org/01/09520123456788/21/12345",
              "name": "EV battery 300Ah",
              "registeredId": "09520123456788.21.12345",
              "idScheme": {
                "type": [
                  "IdentifierScheme"
                ],
                "id": "https://id.gs1.org/01/",
                "name": "Global Trade Identification Number (GTIN)"
              }
            },
            "IDverifiedByCAB": true
          }
        ],
        "assessmentCriteria": [
          {
            "id": "https://www.globalbattery.org/media/publications/gba-rulebook-v2.0-master.pdf#BatteryDisposal",
            "name": "GBA Battery rule book v2.0 battery disposal guidelines",
            "description": "The battery disposal guidelines from the Global Battery Alliance rule book v2.0"
          },
          {
            "id": "https://www.globalbattery.org/media/publications/gba-rulebook-v2.0-master.pdf#BatteryRecycling",
            "name": "GBA Battery rule book v2.0 battery recycling guidelines",
            "description": "The battery recycling guidelines from the Global Battery Alliance rule book v2.0"
          }
        ],
        "conformance": true,
        "conformityTopic": "environment.waste"
      }
    ]
  }
}
